machine:
    pre:
        - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
    services:
        - docker

dependencies:
    override:
        - sudo pip install -U docker-compose
stages:
    - test
test: 
    tags: 
    - docker
    run: 
    - docker-compose up -d

